from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT = "Etude-Talent-Stream.pdf"
BLUE = colors.HexColor("#0055FF")
DARK = colors.HexColor("#10233F")
MID = colors.HexColor("#52657A")
LIGHT = colors.HexColor("#EEF4FF")
PALE = colors.HexColor("#F7F9FC")
GREEN = colors.HexColor("#0A8F55")
ORANGE = colors.HexColor("#D46B08")
RED = colors.HexColor("#B42318")
PURPLE = colors.HexColor("#6D28D9")

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="Brand", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, textColor=BLUE, spaceAfter=18))
styles.add(ParagraphStyle(name="Cover", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=28, leading=31, textColor=DARK, spaceAfter=12))
styles.add(ParagraphStyle(name="Sub", parent=styles["Normal"], fontName="Helvetica", fontSize=12, leading=16, textColor=MID, spaceAfter=14))
styles.add(ParagraphStyle(name="H1x", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=17, leading=20, textColor=DARK, spaceBefore=10, spaceAfter=8, keepWithNext=True))
styles.add(ParagraphStyle(name="H2x", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=12.5, leading=15, textColor=BLUE, spaceBefore=8, spaceAfter=5, keepWithNext=True))
styles.add(ParagraphStyle(name="Bodyx", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.3, leading=12.3, textColor=DARK, spaceAfter=5))
styles.add(ParagraphStyle(name="Smallx", parent=styles["BodyText"], fontName="Helvetica", fontSize=7.6, leading=9.5, textColor=MID, spaceAfter=3))
styles.add(ParagraphStyle(name="Bulletx", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.1, leading=12, leftIndent=11, firstLineIndent=-7, textColor=DARK, spaceAfter=2))
styles.add(ParagraphStyle(name="TH", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=7.5, leading=9, textColor=colors.white))
styles.add(ParagraphStyle(name="TC", parent=styles["BodyText"], fontName="Helvetica", fontSize=7.5, leading=9, textColor=DARK))

def P(text, style="Bodyx"):
    return Paragraph(text, styles[style])

def bullets(items):
    return [Paragraph("• " + x, styles["Bulletx"]) for x in items]

def callout(title, body, fill=LIGHT, accent=BLUE):
    a = ParagraphStyle("cta" + str(id(body)), parent=styles["Bodyx"], fontName="Helvetica-Bold", fontSize=9.6, textColor=accent, leading=12)
    b = ParagraphStyle("ctb" + str(id(body)), parent=styles["Bodyx"], fontSize=9, leading=12, spaceAfter=0)
    t = Table([[Paragraph(title, a), Paragraph(body, b)]], colWidths=[38*mm, 142*mm])
    t.setStyle(TableStyle([("BACKGROUND", (0,0), (-1,-1), fill), ("LINEBEFORE", (0,0), (0,-1), 3, accent), ("VALIGN", (0,0), (-1,-1), "TOP"), ("LEFTPADDING", (0,0), (-1,-1), 7), ("RIGHTPADDING", (0,0), (-1,-1), 7), ("TOPPADDING", (0,0), (-1,-1), 7), ("BOTTOMPADDING", (0,0), (-1,-1), 7)]))
    return t

def table(headers, rows, widths):
    data = [[Paragraph(str(x), styles["TH"]) for x in headers]] + [[Paragraph(str(x), styles["TC"]) for x in row] for row in rows]
    t = Table(data, colWidths=[w*mm for w in widths], repeatRows=1, hAlign="LEFT")
    st = [("BACKGROUND", (0,0), (-1,0), DARK), ("VALIGN", (0,0), (-1,-1), "TOP"), ("GRID", (0,0), (-1,-1), .35, colors.HexColor("#9AA7B8")), ("LEFTPADDING", (0,0), (-1,-1), 4), ("RIGHTPADDING", (0,0), (-1,-1), 4), ("TOPPADDING", (0,0), (-1,-1), 4), ("BOTTOMPADDING", (0,0), (-1,-1), 4)]
    for i in range(1, len(data)):
        if i % 2 == 0:
            st.append(("BACKGROUND", (0,i), (-1,i), PALE))
    t.setStyle(TableStyle(st))
    return t

def flow(items):
    cs = []
    for i, item in enumerate(items):
        st = ParagraphStyle("flow"+str(i)+str(id(items)), parent=styles["TC"], fontName="Helvetica-Bold", fontSize=7.2, leading=8.4, alignment=TA_CENTER)
        cs.append(Paragraph(item, st))
    t = Table([cs], colWidths=[180/len(items)*mm]*len(items))
    commands=[("GRID", (0,0), (-1,-1), .4, colors.HexColor("#C7CFDB")), ("VALIGN", (0,0), (-1,-1), "MIDDLE"), ("TOPPADDING", (0,0), (-1,-1), 6), ("BOTTOMPADDING", (0,0), (-1,-1), 6)]
    for i in range(len(items)):
        commands.append(("BACKGROUND", (i,0), (i,0), LIGHT if i%2==0 else PALE))
    t.setStyle(TableStyle(commands))
    return t

def footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 7.2); canvas.setFillColor(MID)
    canvas.drawRightString(A4[0]-15*mm, A4[1]-9*mm, "JOOBOLO  |  TALENT STREAM")
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(A4[0]/2, 8*mm, "Joboolo - Etude Talent Stream - Septembre 2026 - page %d" % doc.page)
    canvas.restoreState()

story=[]
story += [Spacer(1,38*mm), P("JOOBOLO","Brand"), P("Etude stratégique<br/>Talent Stream","Cover"), P("Transformer les signaux d'intention candidat en connexions recruteur consenties, mesurables et monétisables","Sub"), callout("THÈSE CENTRALE", "La version la plus forte de Talent Stream n'est pas la revente automatique de CV de personnes ayant cliqué. C'est un marché d'intention consentie : Joboolo identifie les signaux d'intérêt, mesure leur intensité, puis révèle progressivement le profil uniquement selon les choix de confidentialité du candidat et les droits du recruteur vérifié."), Spacer(1,10*mm), P("Version 1.0 - 3 septembre 2026"), P("Document d'étude produit et technique. Les observations juridiques sont des points de conception à valider avec un conseil spécialisé avant mise en production.","Smallx"), PageBreak()]

story += [P("Résumé exécutif","H1x"), callout("VERDICT", "Talent Stream mérite une place parmi les fonctionnalités prioritaires de Joboolo. Son potentiel stratégique est estimé à 9,7/10 à condition d'adopter un modèle consent-first et de séparer strictement intention, compatibilité et droit d'accès aux données.", colors.HexColor("#EAF8F0"), GREEN)]
for x in [
"Le recrutement en ligne perd une grande partie du signal situé entre la simple consultation d'une offre et la candidature finalisée. Une personne peut rechercher une offre, la consulter plusieurs fois, la sauvegarder, cliquer vers un ATS externe, commencer une candidature ou déclarer explicitement son intérêt sans jamais devenir une candidature formelle dans l'outil du recruteur.",
"Talent Stream transforme cette zone grise en produit. L'objectif n'est pas d'assimiler chaque clic à une candidature, mais de construire un flux temps réel de talents qui manifestent des niveaux d'intention différents envers une offre précise, puis de permettre une mise en relation progressive et contrôlée.",
"La combinaison décisive est Match Score + Intent Signal. Le Match Score mesure l'adéquation professionnelle ; l'Intent Signal mesure la probabilité d'engagement. Les deux ne doivent jamais être confondus. Leur croisement permet d'identifier des Hot Talents : profils compatibles qui ont aussi manifesté un intérêt récent et suffisamment fort.",
"Pour les offres internes Joboolo, le socle technique existe déjà : candidatures, favoris, profils candidats, CV privés, matching IA et clics de redirection vers les offres partenaires. Pour les offres externes, la première étape réaliste est l'attribution des clics sortants provenant de Joboolo ; la confirmation de candidature doit ensuite passer par des intégrations ATS ou des postbacks signés, plutôt que par un suivi invasif du navigateur.",
"Le modèle économique recommandé n'est pas la vente d'un CV à l'unité. La proposition la plus saine est un abonnement Talent Stream par offre ou un coût par introduction acceptée : le recruteur paie lorsque le candidat accepte la mise en relation et débloque volontairement son profil ou son CV."
]: story.append(P(x))
story += [table(["Dimension","Évaluation"], [["Valeur recruteur","10/10"],["Valeur candidat","9/10"],["Monétisation","10/10"],["Différenciation","9,5/10"],["Effet réseau","10/10"],["Faisabilité interne Joboolo","8/10"],["Faisabilité externe","5,5/10"],["Moat data","10/10"],["Risque vie privée - version naïve","10/10 (critique)"],["Risque vie privée - consent-first","4/10 (maîtrisable)"],["Potentiel stratégique","9,7/10"]],[85,85]), PageBreak()]

story += [P("1. Le problème que Talent Stream veut résoudre","H1x"), P("Le job board classique ne voit réellement un candidat que lorsqu'il postule. Or le parcours d'intention commence bien avant."), flow(["Découverte","Vue","Clic","Retour","Favori","Intérêt déclaré","Début candidature","Candidature"]), Spacer(1,3*mm), P("L'étude Appcast 2025 citée lors de l'analyse porte sur 379 millions de clics et plus de 30 millions de candidatures ; le taux moyen de candidature après clic était de 6,1 %. Le détail varie selon les métiers, mais la leçon produit est claire : le clic et la candidature sont deux étapes très différentes et une grande quantité d'intention n'est pas convertie en candidature."), callout("OPPORTUNITÉ", "Talent Stream cherche à récupérer de la valeur dans cet espace sans transformer artificiellement chaque visiteur en candidat nominatif."), P("1.1 Les trois pertes actuelles","H2x")]
story += bullets(["Perte recruteur : les personnes intéressées mais non candidates disparaissent du funnel.", "Perte candidat : un candidat hésitant n'a souvent qu'un choix binaire entre ne rien faire et remplir une candidature complète.", "Perte plateforme : les signaux de recherche, sauvegarde, clic et retour servent rarement à créer une connexion humaine directe et consentie."])
story += [P("1.2 La promesse commerciale","H2x"), callout("PROMESSE TALENT STREAM", "Au lieu de chercher des candidats qui pourraient être intéressés, le recruteur accède à un flux de talents qui ont déjà manifesté une intention envers son offre - tout en respectant le niveau de partage choisi par le candidat.", colors.HexColor("#F6F0FF"), PURPLE)]

story += [P("2. Positionnement par rapport au marché","H1x"), P("Le concept d'utiliser des signaux d'intention est validé par plusieurs acteurs, mais Talent Stream peut aller plus loin en liant les signaux à une offre précise, au matching et à une mécanique de révélation progressive."), table(["Acteur / approche","Signal ou capacité","Écart exploitable par Joboolo"], [["LinkedIn Recruiter","Spotlights, Open to Work, Active talent, Interested in your company","Le signal est souvent entreprise/profil ; Talent Stream peut être centré sur une offre précise et la permission de partage."],["Indeed Smart Sourcing","Compétences, activité de recherche, récence","Joboolo peut ajouter une chronologie d'intention autour d'une offre précise et des introductions acceptées."],["Avature / CRM candidats","Parcours site carrière, recherches, engagement","Talent Stream peut rendre cette intelligence accessible aux PME sans déployer un CRM enterprise complet."],["ATS traditionnels","Candidats ayant postulé","Ils voient mal les intéressés non convertis et les signaux en amont."]],[48,62,70]), P("La différenciation ne vient donc pas de l'idée générale 'observer l'intention', mais du produit combiné : offre précise + intention récente + compatibilité + consentement + introduction mesurable.")]

story += [P("3. Deux notions à séparer absolument","H1x"), P("3.1 Intention observée","H2x"), P("Une intention observée provient d'un comportement : consultation, retour, clic sortant, recherche proche, lecture de page entreprise. Elle peut aider à personnaliser Joboolo ou à produire des statistiques, mais elle ne doit pas être interprétée automatiquement comme une autorisation de transmettre l'identité ou le CV au recruteur."), P("3.2 Intention déclarée","H2x"), P("Une intention déclarée est un acte volontaire : sauvegarde assortie d'un partage, bouton 'Je suis intéressé(e)', autorisation de contact, candidature ou acceptation d'une invitation recruteur."), callout("RÈGLE PRODUIT", "Intention observée = signal de pertinence. Intention déclarée = base possible pour une mise en relation, selon le texte de consentement et les permissions choisies.", colors.HexColor("#FFF7ED"), ORANGE), P("3.3 Intent Score et Match Score","H2x"), table(["Exemple","Intent","Match","Lecture"], [["Candidat A","95 %","42 %","Très intéressé mais peu compatible"],["Candidat B","45 %","94 %","Très compatible mais à convaincre"],["Candidat C","90 %","92 %","Hot Talent prioritaire"],["Candidat D","20 %","55 %","Faible priorité"]],[35,25,25,95]), P("L'intérêt ne doit jamais améliorer artificiellement le score de compétence. Il mesure une autre dimension : la probabilité d'engagement."), PageBreak()]

story += [P("4. Modèle de signaux et révélation progressive","H1x"), table(["Signal","Intent indicatif","Visibilité recruteur recommandée"], [["Vue simple","10","Statistiques anonymes uniquement"],["Plusieurs consultations récentes","25","Agrégat / profil anonyme"],["Clic vers offre externe","40","Intérêt anonyme"],["Retours récurrents","50","Intérêt anonyme élevé"],["Favori privé","60","Rien de nominatif par défaut"],["Favori + partage Talent Stream","75","Profil selon autorisation"],["Je suis intéressé(e)","85","Profil visible selon autorisation"],["Début candidature externe confirmé","90","Profil selon autorisation"],["Candidature","100","Candidature + CV sélectionné"],["Invitation recruteur acceptée","100","Profil/CV selon grant"]],[58,31,91]), P("Ces valeurs sont des exemples de conception, pas un modèle final. Le futur moteur devrait privilégier des niveaux explicites - faible, moyen, fort, très fort - et afficher au recruteur le signal concret et sa récence plutôt qu'un score opaque à plusieurs décimales."), P("4.1 Décroissance temporelle","H2x"), P("L'intention vieillit rapidement. Un favori d'il y a deux heures est beaucoup plus actionnable qu'un favori de sept mois. Talent Stream doit donc utiliser une fonction de récence et conserver l'événement source."), callout("PRINCIPE", "Signal x récence x répétition, avec explication lisible pour le recruteur.")]

story += [P("5. Expérience candidat","H1x"), P("5.1 Le nouveau bouton clé : Je suis intéressé(e)","H2x"), P("Entre 'Sauvegarder' et 'Postuler', Joboolo peut proposer une action légère : 'Je suis intéressé(e)'. Elle signifie que la personne n'est pas forcément prête à remplir une candidature complète, mais accepte que le recruteur considère son profil pour cette opportunité selon les permissions affichées."), flow(["Voir offre","Sauvegarder","Je suis intéressé(e)","Choisir ce qui est partagé","Recruteur peut inviter"]), P("5.2 Le favori reste privé par défaut","H2x"), P("Joboolo gère déjà les favoris candidats. Un favori peut toutefois simplement signifier 'à lire plus tard'. Il ne doit donc pas déclencher automatiquement un partage nominatif."), callout("UX PROPOSÉE", "Offre sauvegardée. Voulez-vous aussi signaler votre intérêt au recruteur ? [Partager mon intérêt] [Non merci]", PALE, DARK), P("5.3 Choix du CV","H2x"), P("Joboolo permet déjà au candidat de conserver plusieurs documents. Talent Stream devrait lui permettre de choisir quel CV précis est partagé pour une offre, ainsi que la durée de l'autorisation.")]
story += bullets(["Profil uniquement.", "Profil + CV sélectionné.", "Profil + CV + moyen de contact direct.", "Autorisation pour cette offre uniquement.", "Expiration automatique, par exemple après 30 jours.", "Retrait possible à tout moment pour les usages futurs."])
story += [P("5.4 Invitation d'un talent anonyme","H2x"), P("Un recruteur peut voir qu'un excellent profil anonyme a manifesté de l'intérêt, puis demander à Joboolo d'envoyer une invitation. La personne choisit ensuite si elle souhaite révéler son profil."), flow(["Talent anonyme","Invitation recruteur","Notification Joboolo","Candidat accepte","Grant créé","Profil révélé"])]

story += [P("6. Expérience recruteur","H1x"), P("L'écran recruteur ne doit plus se limiter au nombre de candidatures. Il doit représenter le funnel d'intention et mettre en avant le quadrant Match élevé + Intention élevée."), table(["Talent","Match","Intention","Signal","Action"], [["Sophie M.","94 %","Très forte","Candidature","Voir / contacter"],["Karim B.","91 %","Très forte","Intéressé aujourd'hui","Voir / inviter"],["Laura P.","88 %","Forte","Favori partagé","Voir / inviter"],["Anonyme #142","95 %","Forte","Retours + clic","Demander introduction"],["Anonyme #184","90 %","Moyenne","Clic externe","Statistiques / invitation si éligible"]],[34,20,28,47,51]), P("6.1 Trois compteurs simples","H2x"), table(["Catégorie","Définition"], [["Applicants","Candidatures formelles reçues"],["Warm Talents","Profils compatibles ayant manifesté une intention partageable ou acceptant d'être invités"],["Potential Talents","Signaux anonymes compatibles utiles pour mesurer le potentiel du funnel"]],[45,135]), P("6.2 Hot Talent","H2x"), callout("HOT TALENT", "Match élevé + intention élevée + signal récent + permission suffisante pour une mise en relation.", colors.HexColor("#FFF1F1"), RED), P("6.3 Insight recruteur","H2x"), P("Talent Stream peut devenir un outil de diagnostic, pas seulement un flux de profils. Exemple : '26 candidats compatibles ont consulté votre offre mais seulement 3 ont postulé.' Cela peut indiquer un problème de friction, salaire, clarté de l'offre ou processus externe."), PageBreak()]

story += [P("7. Adéquation avec le code Joboolo actuel","H1x"), P("Talent Stream est particulièrement intéressant parce qu'une partie importante du socle existe déjà dans le repository."), table(["Brique existante","État utile pour Talent Stream"], [["Favoris candidats","saved_jobs stocke user_id, job_id et created_at."],["Candidatures","applications stocke candidate_id, job_id, cv_url, cover_letter et status."],["CV privés","candidate_documents et files gèrent des documents privés et plusieurs CV."],["ACL documents","L'employeur ne peut lire un CV que lorsqu'une candidature autorisée le référence explicitement."],["Matching IA","Endpoints candidat et recruteur existent déjà pour analyser la compatibilité."],["Clics offres partenaires","POST /jobs/{job_id}/click enregistre click_events et redirige vers l'URL externe."],["Profils","skills, experience_years, location et autres attributs sont déjà présents."]],[50,130]), P("7.1 Limite actuelle du clic externe","H2x"), P("Le clic partenaire actuel n'est pas authentifié et click_events ne contient pas candidate_id. Joboolo sait qu'un clic a eu lieu, mais pas quelle personne authentifiée l'a effectué. Pour Talent Stream, il ne faut pas simplement ajouter candidate_id au mécanisme CPC existant : les événements de facturation et les événements d'intention doivent rester séparés."), callout("DÉCISION ARCHITECTURE", "Ne pas mélanger CPC et intention candidat. Créer un event store Talent Stream dédié et faire du lien avec la facturation uniquement lorsque nécessaire.", colors.HexColor("#FFF7ED"), ORANGE), P("7.2 Ne pas affaiblir les ACL CV","H2x"), P("L'ACL actuelle est volontairement stricte : propriétaire candidat, administrateur explicite, ou employeur dont une candidature référence exactement le document sur sa propre offre. Talent Stream doit ajouter un quatrième chemin explicite : un talent_stream_grant actif et ciblé, jamais un accès général aux CV.")]

story += [P("8. Architecture de données proposée","H1x"), P("8.1 talent_intent_events","H2x"), table(["Champ","Rôle"], [["candidate_id","Identité interne si l'événement est associé à un candidat authentifié."],["job_id","Offre canonique Joboolo."],["event_type","view, external_click, save, interest, apply_started, apply_completed, invitation_accepted."],["source","joboolo, partner_redirect, ats_postback, etc."],["occurred_at","Horodatage UTC."],["consent_state","État de partage au moment de l'événement."],["session / attribution","Identifiant technique minimal pour éviter doublons et attribution incorrecte."]],[50,130]), P("8.2 talent_stream_grants","H2x"), table(["Champ","Rôle"], [["candidate_id","Candidat qui donne l'autorisation."],["job_id","Offre précise."],["company_id / recruiter scope","Entité autorisée."],["share_profile","Profil Joboolo autorisé ou non."],["share_cv","CV autorisé ou non."],["cv_document_id","Document précis choisi."],["created_at / expires_at","Fenêtre d'autorisation."],["revoked_at","Retrait de l'autorisation."],["source","interest_button, invite_accept, application, etc."]],[50,130]), P("8.3 talent_stream_contact_requests","H2x")]
story += bullets(["recruiter_id", "candidate_id ou identifiant anonyme résolvable par Joboolo", "job_id", "status : pending / accepted / declined / expired", "created_at / answered_at"])
story += [P("8.4 external_job_connections","H2x")]
story += bullets(["job_id canonique", "canonical_external_url", "company_id", "verified_owner", "ats_type", "integration_type", "conversion_secret / webhook metadata sécurisée"])

story += [P("9. Talent Stream Anywhere : ce qui est réellement possible","H1x"), table(["Situation","Niveau de faisabilité"], [["Offre hébergée sur Joboolo","Oui - complet"],["Offre partenaire visible sur Joboolo puis redirection","Oui - clic attribuable ; candidature externe à confirmer"],["Offre externe ouverte depuis Joboolo","Oui - clic sortant attribuable"],["ATS connecté avec postback/webhook","Oui - candidature confirmable"],["ATS externe sans intégration","Partiel - Joboolo ne peut pas connaître avec certitude la candidature finale"],["Offre trouvée directement ailleurs sans passer par Joboolo","Non sans intégration ou action volontaire du candidat"]],[112,68]), P("9.1 Niveau 1 - Redirect Joboolo","H2x"), P("Le plus simple est d'attribuer les clics sortants depuis les pages Joboolo. C'est proche du système partenaire déjà présent et permet de mesurer un signal sans instrumenter le site de l'employeur."), P("9.2 Niveau 2 - ATS Postback","H2x"), P("Le meilleur modèle long terme consiste à demander à l'ATS ou au site carrière de confirmer les conversions : candidature commencée, candidature terminée, voire étape de recrutement. Le postback doit être signé, idempotent et ne transporter que les données strictement nécessaires."), P("9.3 Niveau 3 - Joboolo Connect","H2x"), P("Un SDK sur le site carrière pourrait mesurer certaines étapes, mais il augmente fortement les obligations de transparence, consentement et gouvernance des traceurs. Ce n'est pas la première version recommandée."), P("9.4 Extension navigateur : non recommandée au lancement","H2x"), P("Une extension qui suivrait les sites emploi visités offrirait une couverture impressionnante mais créerait un coût de confiance et de conformité disproportionné. Le risque de perception 'Joboolo surveille ma recherche d'emploi partout' est trop fort."), PageBreak()]

story += [P("10. Confidentialité et RGPD : construire le produit autour du consentement","H1x"), P("Le coeur du risque n'est pas l'analyse statistique d'un funnel, mais la révélation nominative d'un profil ou d'un CV à partir d'un comportement que la personne ne s'attendait pas à voir transmis. Le produit doit donc être Privacy by Design."), P("10.1 Réglage candidat","H2x"), table(["Mode","Comportement"], [["Désactivé","Aucune mise en relation Talent Stream nominative."],["Me demander à chaque offre","Joboolo demande avant tout partage."],["Après Je suis intéressé(e)","Partage uniquement lorsque le candidat active explicitement cette action."],["Favoris partagés","Le favori reste privé ; le candidat peut choisir de le convertir en signal partagé."]],[55,125]), P("La version 'autoriser automatiquement après chaque clic' est déconseillée : le clic est un signal trop ambigu et l'effet serait surprenant pour l'utilisateur."), P("10.2 Finalité et minimisation","H2x")]
story += bullets(["Expliquer clairement la finalité de Talent Stream avant le partage.", "Limiter le partage à l'offre ou à l'entreprise spécifiée.", "N'exposer que les données nécessaires.", "Prévoir expiration et révocation.", "Journaliser les grants et accès pour audit.", "Distinguer statistiques anonymes, profil pseudonyme et profil nominatif."])
story += [P("10.3 Cookies et traceurs externes","H2x"), P("La CNIL rappelle que les traceurs non strictement nécessaires nécessitent en principe un consentement, et qu'un mécanisme permettant le suivi entre plusieurs sites ne rentre pas dans la simple exemption de mesure d'audience. Cela renforce la recommandation d'utiliser d'abord les redirections Joboolo et les intégrations ATS plutôt qu'un SDK comportemental cross-site."), P("10.4 Recrutement et contrôle CNIL","H2x"), P("Le recrutement fait partie des thèmes de contrôle prioritaires annoncés par la CNIL pour 2026, notamment sur l'information, les traitements automatisés et les durées de conservation. Talent Stream doit donc avoir une politique documentaire et de rétention définie avant généralisation.")]

story += [P("11. Sécurité et anti-abus","H1x"), P("Talent Stream concentre des données sensibles commercialement et personnellement. Un faux recruteur ne doit jamais pouvoir créer une offre et aspirer des centaines de CV."), table(["Contrôle","Exigence"], [["Verified Recruiter","Compte recruteur vérifié avant accès nominatif."],["Domaine entreprise","Email professionnel et correspondance avec l'entreprise."],["Ownership offre","Prouver que le recruteur gère ou mandate réellement l'offre."],["Scope minimal","Grant limité à une offre / entreprise / document."],["Rate limits","Limiter invitations, exports et consultations massives."],["Audit log","Tracer qui a consulté quoi et sur quelle base."],["Partenaires XML","Un distributeur de trafic n'est pas automatiquement un recruteur autorisé."],["Détection abus","Suspension et investigation sur volumes ou comportements anormaux."]],[50,130]), P("11.1 Partenaires XML : distinction indispensable","H2x"), callout("RÈGLE", "traffic_partner != authorized_recruiter. Le fait de fournir un feed ou de payer au CPC ne donne aucun droit automatique sur les CV.", colors.HexColor("#FFF1F1"), RED)]

story += [P("12. Modèles économiques","H1x"), P("Le produit doit éviter le message implicite 'Joboolo vend vos CV'. La facturation doit porter sur l'accès à une fonctionnalité de recrutement et sur la création d'une connexion consentie."), table(["Modèle","Avantages","Limites"], [["Abonnement Talent Stream par offre","Simple à comprendre, prévisibilité revenu","Risque de faible usage sur certaines offres"],["Pack d'introductions","Très lié à la valeur","Nécessite définition précise d'une introduction"],["Pay per Accepted Introduction","Alignement candidat / recruteur / Joboolo","Facturation et anti-contournement à concevoir"],["Bundle Premium + Talent Stream","Augmente fortement la valeur des offres Premium existantes","Doit garder une offre accessible aux petites entreprises"]],[54,66,60]), P("12.1 Modèle recommandé : Pay per Accepted Introduction","H2x"), flow(["Recruteur invite","Joboolo notifie","Candidat refuse -> 0","Candidat accepte","Profil débloqué","Crédit consommé"]), P("Ce modèle aligne les incentives : Joboolo est rémunéré lorsqu'il crée effectivement une possibilité de contact désirée par les deux parties."), P("12.2 Synergie avec les offres Premium","H2x"), P("Joboolo possède déjà un produit d'offres Premium. Talent Stream peut devenir la justification fonctionnelle d'un prix premium plus forte que la simple mise en avant visuelle : visibilité + matching + Warm Talents + invitations + analytics."), PageBreak()]

story += [P("13. Talent Stream comme outil d'intelligence recrutement","H1x"), P("Le flux d'intention peut expliquer pourquoi une offre convertit mal. C'est un produit de données pour le recruteur, même lorsque les personnes restent anonymes."), table(["Observation","Interprétation possible","Action"], [["Beaucoup de vues, peu de clics","Titre, salaire ou marque peu convaincants","Optimiser l'annonce"],["Beaucoup de clics, peu de candidatures","Friction ATS externe ou formulaire trop long","Simplifier le processus"],["Beaucoup de bons matchs anonymes, peu d'intérêts déclarés","Proposition peu attractive","Revoir salaire / remote / contenu"],["Beaucoup de Warm Talents, peu d'invitations acceptées","Réputation recruteur ou message faible","Améliorer approche et transparence"],["Bonne conversion mais faible qualité","Ciblage / matching à recalibrer","Revoir critères et données"]],[55,72,53]), P("13.1 Avec un catalogue très large","H2x"), P("Avec l'objectif Joboolo d'agréger potentiellement un très grand nombre d'annonces, Talent Stream peut produire un Intent Graph : qui s'intéresse à quel type de poste, entreprise, compétence, lieu et conditions, à quel moment. Cette donnée peut renforcer recommandations, market intelligence et sourcing - à condition de conserver une gouvernance stricte et de ne pas transformer le graphe en mécanisme de surveillance opaque."), callout("MOAT POTENTIEL", "LinkedIn a le social graph. Les grands moteurs ont le search graph. Joboolo peut chercher à construire un Intent Graph consent-first : intention + compatibilité + récence + permission.", colors.HexColor("#F6F0FF"), PURPLE)]

story += [P("14. IA, scoring et explicabilité","H1x"), P("Si Talent Stream se contente d'afficher des événements et des permissions, le risque de décision automatisée est limité. En revanche, des classements automatiques de candidats pour l'emploi doivent être traités comme une fonction fortement réglementée et auditable.")]
story += bullets(["Afficher les critères professionnels utilisés par le Match Score.", "Ne jamais laisser l'Intent Score modifier le score de compétence.", "Conserver l'intervention humaine dans les décisions de recrutement.", "Journaliser version modèle, données d'entrée pertinentes et résultat quand l'IA classe des candidats.", "Exclure les attributs sensibles et proxies injustifiés.", "Permettre au recruteur de comprendre pourquoi un profil est recommandé."])
story += [P("Les systèmes d'IA utilisés pour le recrutement figurent parmi les usages à haut risque du cadre européen. L'analyse précédente retenait une date d'application des obligations principales correspondantes au 2 décembre 2027 après les évolutions réglementaires de 2026. Une vérification juridique actualisée devra être faite au moment de l'industrialisation."), P("15. Roadmap d'implémentation recommandée","H1x"), table(["Phase","Périmètre","Objectif"], [["TS1","Candidatures Joboolo dans le nouveau flux","Unifier le dashboard sans nouveau signal comportemental"],["TS2","Bouton Je suis intéressé(e)","Créer le premier signal d'intention explicite"],["TS3","Favori + option de partage","Convertir un favori privé en signal volontaire"],["TS4","Clics anonymes + analytics","Mesurer le funnel sans révéler identité"],["TS5","Invitation recruteur -> candidat","Créer la révélation progressive"],["TS6","Talent Stream + Match Score","Identifier Hot Talents"],["TS7","Offres partenaires redirigées","Étendre les signaux externes venant de Joboolo"],["TS8","Conversion externe signée","Confirmer apply_started / apply_completed"],["TS9","Intégrations ATS","Industrialiser conversion et statuts"],["TS10","Talent Stream Anywhere","Connexion d'offres externes vérifiées"]],[17,64,99]), P("15.1 MVP recommandé","H2x"), callout("MVP", "TS1 à TS6 suffisent déjà pour tester la proposition de valeur : flux recruteur, Je suis intéressé(e), favoris partagés, invitations, consentement et croisement avec le Match Score.", colors.HexColor("#EAF8F0"), GREEN), P("Ce MVP évite les intégrations ATS et le tracking externe complexe. Il permet de mesurer si les candidats acceptent le concept et si les recruteurs paient pour des introductions mieux qualifiées.")]

story += [P("16. KPI de validation","H1x"), table(["KPI","Question produit"], [["Activation Talent Stream","Les candidats comprennent-ils et acceptent-ils le modèle ?"],["Favori -> intérêt partagé","Le passage du privé au partage est-il naturel ?"],["Invitation -> acceptation","Le signal d'intention produit-il des contacts utiles ?"],["Stream -> candidature","Le flux augmente-t-il la conversion ?"],["Stream -> entretien","La qualité est-elle supérieure à un sourcing froid ?"],["Stream -> embauche","KPI ultime de valeur"],["Temps au premier Hot Talent","Vitesse de valeur pour le recruteur"],["Opt-out / révocation","Indicateur de confiance et de friction"],["Signalements recruteurs","Mesure des abus"],["Revenu par offre / introduction","Validation de monétisation"]],[58,122]), P("16.1 KPI à ne pas optimiser seul","H2x"), callout("ATTENTION", "Le nombre de CV révélés n'est pas le KPI principal. L'objectif est le nombre de connexions utiles, entretiens et recrutements supplémentaires créés par Talent Stream.", colors.HexColor("#FFF7ED"), ORANGE)]

story += [P("17. Risques principaux et garde-fous","H1x"), table(["Risque","Gravité","Garde-fou"], [["Transmission surprise après clic","Critique","Aucun partage nominatif basé uniquement sur un clic"],["Faux recruteur / harvesting","Critique","Vérification entreprise + ownership + rate limits"],["Confusion favori = candidature","Élevée","Favori privé par défaut"],["Score opaque","Élevée","Séparer Match et Intent, afficher les raisons"],["Tracking cross-site","Élevée","Préférer redirect et ATS postback"],["Partenaire feed recevant des CV","Critique","traffic_partner != authorized_recruiter"],["Conservation excessive","Élevée","Expiration grants et politique de rétention"],["Biais recrutement IA","Élevée","Critère professionnel, audit, humain dans la boucle"]],[65,28,87])]

story += [P("18. Conclusion stratégique","H1x")]
for x in [
"Talent Stream peut devenir une des fonctions les plus distinctives de Joboolo parce qu'il exploite un actif que les ATS voient mal : l'intention avant candidature. Mais son succès dépend entièrement de la façon dont cette intention est convertie en accès aux données personnelles.",
"La version naïve - transmettre le CV des personnes qui ont cliqué - maximiserait la valeur apparente à court terme mais créerait un problème de confiance, de conformité et de réputation. La version consent-first est plus forte : le clic signale une opportunité ; le candidat contrôle la révélation ; le recruteur paie pour une introduction acceptée ou pour l'accès au produit Talent Stream.",
"Le produit doit être construit autour de quatre primitives durables : événement d'intention, Match Score indépendant, grant explicite et recruteur vérifié. Ces primitives pourront ensuite alimenter Talent Rediscovery, recommandations, sourcing, analytics, Job Trust Score et Market Intelligence.",
"Stratégiquement, Talent Stream + Match Engine forme un candidat naturel au coeur B2B de Joboolo : moins de sourcing froid, plus de signaux chauds, des connexions plus rapides et un nouveau modèle de monétisation qui ne repose pas sur la vente brute de données personnelles."
]: story.append(P(x))
story += [callout("RECOMMANDATION FINALE", "Conserver Talent Stream dans la shortlist prioritaire. Concevoir d'abord TS1-TS6 en consent-first, mesurer l'acceptation candidat et la valeur recruteur, puis n'ouvrir Talent Stream Anywhere qu'avec des recruteurs vérifiés et des intégrations externes contrôlées.", colors.HexColor("#EAF8F0"), GREEN), PageBreak(), P("19. Sources et références utilisées dans l'étude","H1x"), P("Les liens ci-dessous correspondent aux sources citées dans l'analyse initiale. Les pages et règles peuvent évoluer ; elles devront être revalidées avant spécification juridique finale ou lancement commercial.")]
for title, url in [
("Appcast - 2025 Recruitment Marketing Benchmark Report","https://www.appcast.io/the-2025-recruitment-marketing-benchmark-report-is-live/"),
("LinkedIn Recruiter - Spotlights","https://www.linkedin.com/help/recruiter/answer/a414283"),
("LinkedIn - I'm interested feature","https://www.linkedin.com/help/linkedin/answer/a1378526"),
("Indeed - Recruiter / Smart Sourcing resources","https://www.indeed.com/hire/resources/howtohub/how-to-use-indeed-as-a-recruiter"),
("Avature - Candidate Relationship Management","https://www.avature.net/fr/gestion-relation-candidats/"),
("CNIL - Guide recrutement et données personnelles","https://cnil.fr/sites/default/files/atoms/files/guide_referentiel_-_recrutement.pdf"),
("CNIL - Recrutement et données personnelles TPE/PME","https://www.cnil.fr/fr/recrutement-et-donnees-personnelles-dans-les-tpepme-cinq-questions-incontournables-se-poser"),
("CNIL - Cookies et autres traceurs, FAQ","https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/FAQ"),
("CNIL - Contrôles prioritaires 2026","https://www.cnil.fr/fr/controles-prioritaires-2026"),
("Commission européenne - cadre réglementaire IA","https://digital-strategy.ec.europa.eu/fr/policies/regulatory-framework-ai"),
("EUR-Lex - Règlement (UE) 2024/1689 sur l'IA","https://eur-lex.europa.eu/eli/reg/2024/1689/2026-07-27/eng/pdf")]:
    story.append(P("<b>%s</b><br/>%s" % (title, url), "Smallx"))
story += [P("20. Points du repository Joboolo examinés","H1x")]
story += bullets(["backend/routes/saved_jobs.py - favoris candidats.", "backend/routes/applications.py - candidatures et informations candidat visibles au recruteur propriétaire.", "backend/routes/jobs.py - recherche, offres, redirection et click_events partenaire.", "backend/routes/files.py - documents candidats privés et ACL d'accès.", "backend/routes/ai.py et backend/ai_service.py - matching et recommandations.", "backend/models.py - profils, offres, candidatures et favoris.", "backend/routes/recruiter.py - produit recruteur Premium et paiements."])

pdf = SimpleDocTemplate(OUT, pagesize=A4, rightMargin=15*mm, leftMargin=15*mm, topMargin=17*mm, bottomMargin=14*mm, title="Etude Talent Stream", author="Joboolo / ChatGPT")
pdf.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
