"""A11 G1: real Mongo standalone, isolated random databases; no shared DB fallback.

A11_MONGO_URL must point to the disposable CI/local loopback standalone container.
No environment application configuration, credentials or production database used.
"""
import asyncio
from copy import deepcopy
from dataclasses import replace
import os
from urllib.parse import urlsplit
import uuid

import pytest
import pytest_asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from pymongo.errors import AutoReconnect, DuplicateKeyError

from domains.intent.serialization import event_from_document, event_to_document
from domains.intent.service import IntentEventConflictError, IntentEventService
from scripts.migrate_ts_a11_intent_event_indexes import INDEX_NAME, IntentMigrationError, migrate
from test_ts_a11_intent_events import event, NOW


@pytest_asyncio.fixture
async def db():
    url=os.environ.get('A11_MONGO_URL')
    if not url:
        pytest.skip('A11_MONGO_URL must designate a disposable standalone Mongo')
    parsed=urlsplit(url)
    if (parsed.scheme!='mongodb' or parsed.hostname!='127.0.0.1' or parsed.port is None
            or parsed.netloc!=f'127.0.0.1:{parsed.port}' or parsed.path not in ('','/')
            or parsed.query or parsed.fragment):
        pytest.fail('A11 G1 accepts only an explicit loopback port, no credentials/database/options')
    client=AsyncIOMotorClient(url,serverSelectionTimeoutMS=5000)
    name='test_ts_a11_'+uuid.uuid4().hex
    try:
        hello=await client.admin.command('hello')
        assert 'setName' not in hello, 'A11 must prove standalone compatibility without transactions'
        yield client[name]
    finally:
        # Only the database generated by this fixture is ever removed.
        assert name.startswith('test_ts_a11_') and len(name)==44
        await client.drop_database(name)
        client.close()


@pytest.mark.asyncio
async def test_real_identity_and_partial_key_uniqueness(db):
    await migrate(db,apply=True)
    coll=db.talent_intent_events
    doc=event_to_document(event(idempotency_key='key'))
    await coll.insert_one(doc)
    with pytest.raises(DuplicateKeyError): await coll.insert_one(deepcopy(doc))
    with pytest.raises(DuplicateKeyError): await coll.insert_one({**doc,'_id':'other'})
    # Optional means absent, not a shared null key.
    await coll.insert_one(event_to_document(event(event_id='without-1')))
    await coll.insert_one(event_to_document(event(event_id='without-2')))
    assert await coll.count_documents({})==3


@pytest.mark.asyncio
@pytest.mark.parametrize('key',[None,'key'])
async def test_concurrent_identical_records_have_one_canonical_event(db,key):
    await migrate(db,apply=True)
    service=IntentEventService(db); obj=event(idempotency_key=key)
    results=await asyncio.gather(*(service.record(obj) for _ in range(20)))
    assert all(result==obj for result in results)
    assert await db.talent_intent_events.count_documents({})==1


@pytest.mark.asyncio
@pytest.mark.parametrize('same_identity',[False,True])
async def test_concurrent_conflicting_records_have_one_winner(db,same_identity):
    await migrate(db,apply=True)
    service=IntentEventService(db)
    first=event(idempotency_key='key')
    second=replace(first,event_id=first.event_id if same_identity else 'event-2',job_id='job-2')
    results=await asyncio.gather(service.record(first),service.record(second),return_exceptions=True)
    assert sum(isinstance(result,IntentEventConflictError) for result in results)==1
    winner=next(result for result in results if not isinstance(result,Exception))
    stored=await db.talent_intent_events.find_one({})
    assert event_from_document(stored)==winner
    assert await db.talent_intent_events.count_documents({})==1


@pytest.mark.asyncio
async def test_retry_after_committed_insert_with_lost_response(db,monkeypatch):
    await migrate(db,apply=True)
    service=IntentEventService(db); obj=event(idempotency_key='key')
    original=service.repo.insert
    async def insert_then_disconnect(document):
        await original(document)
        raise AutoReconnect('synthetic lost response after committed insert')
    monkeypatch.setattr(service.repo,'insert',insert_then_disconnect)
    with pytest.raises(AutoReconnect): await service.record(obj)
    monkeypatch.setattr(service.repo,'insert',original)
    assert await service.record(obj)==obj
    assert await db.talent_intent_events.count_documents({})==1


@pytest.mark.asyncio
async def test_bson_roundtrip_and_full_payload_conflict(db):
    await migrate(db,apply=True)
    service=IntentEventService(db); obj=event(idempotency_key='key',source_organization_id='source')
    await service.record(obj)
    stored=await db.talent_intent_events.find_one({'_id':obj.event_id})
    assert stored['occurred_at'].tzinfo is None and stored['occurred_at'].microsecond==123000
    assert event_from_document(stored)==obj
    with pytest.raises(IntentEventConflictError):
        await service.record(replace(obj,source_organization_id='changed'))
    assert await db.talent_intent_events.find_one({'_id':obj.event_id})==stored


@pytest.mark.asyncio
async def test_migration_is_read_only_by_default_and_repeatable(db):
    assert (await migrate(db))['idempotency_index_ready'] is False
    assert 'talent_intent_events' not in await db.list_collection_names()
    await migrate(db,apply=True)
    await migrate(db,apply=True)
    indexes=await db.talent_intent_events.index_information()
    assert set(indexes)=={'_id_',INDEX_NAME}
    assert indexes[INDEX_NAME]['unique'] is True
    assert indexes[INDEX_NAME]['partialFilterExpression']=={'idempotency_key':{'$type':'string'}}
    assert all('expireAfterSeconds' not in spec for spec in indexes.values())


@pytest.mark.asyncio
@pytest.mark.parametrize('bad_kind',['malformed','duplicate_key'])
async def test_migration_rejects_invalid_data_before_creating_index(db,bad_kind):
    coll=db.talent_intent_events
    if bad_kind=='malformed':
        await coll.insert_one({'_id':'bad','subject':{'candidate_id':'candidate'}})
    else:
        await coll.insert_one(event_to_document(event(idempotency_key='same')))
        await coll.insert_one(event_to_document(event(event_id='second',idempotency_key='same')))
    before=await coll.find({}).to_list(length=10)
    with pytest.raises(IntentMigrationError): await migrate(db,apply=True)
    assert set(await coll.index_information())=={'_id_'}
    assert await coll.find({}).to_list(length=10)==before


@pytest.mark.asyncio
async def test_corruption_cannot_be_returned_as_a_successful_retry(db):
    await migrate(db,apply=True)
    bad=event_to_document(event(idempotency_key='key')); bad['permission']=True
    await db.talent_intent_events.insert_one(bad)
    before=await db.talent_intent_events.find_one({'_id':bad['_id']})
    with pytest.raises(IntentEventConflictError):
        await IntentEventService(db).record(event(idempotency_key='key'))
    assert await db.talent_intent_events.find_one({'_id':bad['_id']})==before


@pytest.mark.asyncio
async def test_migration_refuses_existing_ttl_without_dropping_it(db):
    coll=db.talent_intent_events
    await coll.create_index('retention_until',name='unexpected_ttl',expireAfterSeconds=0)
    with pytest.raises(IntentMigrationError): await migrate(db,apply=True)
    assert set(await coll.index_information())=={'_id_','unexpected_ttl'}
